#!/usr/local/bin/perl

open (DEEP, 'deep_thoughts') || die "$!\n";
open (T1, '>thoughts1') || die "$!\n";
open (T2, '>thoughts2') || die "$!\n";

WEIRD: {
    $which = rand () < 0.5 ? \*T1 : \*T2;
    while (<DEEP>) {
	print $which $_;
	redo WEIRD if /^\s*$/;
    }
}

close T2;
close T1;
close DEEP;
